elasticsearch:
  host: http://35.202.7.252
  port: 9200

spring:
  #  redis:
  #    host: 34.122.84.61
  #    port: 6379
  #    password:
  #    lettuce:
  #      pool:
  #        max-wait: 100
  #        max-active: 500
  #        max-idle: 500
  #        min-idle: 50
  #    connect-timeout: 500
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'

  datasource:
    username: connectuser
    password: connect123!@#
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://34.123.231.69:3306/connectdb?serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=utf8
    maximumPoolSize: 100
    minimumIdle: 100

  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    open-in-view: false

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
        use_sql_comments: true

  cache:
    cache-names: category_list_cache,product_cache

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  thymeleaf:
    cache: false

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

